apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: gpu-2-spot
spec:
  whenUnsatisfiable: ScaleUpAnyway
  priorities:
  - machineType: g4-standard-48
    spot: true
  - machineType: g4-standard-48
    spot: false

  nodePoolAutoCreation:
    enabled: true
