apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: gpu-2-spot
spec:
  whenUnsatisfiable: ScaleUpAnyway
  priorities:
  - machineType: g2-standard-8
    spot: true
  - machineType: g2-standard-8
    spot: false
  nodePoolAutoCreation:
    enabled: true
